### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by maelle** [dmi3kno/hocr#1]
First of all, what a cool package, I really like the image in the README and I didn't know about hOCR before, nice stuff!

I have a few comments:

* I see a typo "ragrding"

* I'd find it easier to read the README if packages were not loaded in an hidden chunk, and even better with the `pkg::fun` syntax in order to see better what's from this package vs. other packages.

* I was wondering whether you could plot the image directly see e.g. https://cran.r-project.org/web/packages/magick/vignettes/intro.html#raster_images

**Comment by dmi3kno** [comment]
- Will fix typos
- Will namespace functions, where reasonable (trade-off against code readability). 
- I need a `grob` object in order to `patchwork` it with `ggplot`. And the point of showing bbox as `geom_rectangle` is precisely that: once data is in `tibble`, you can do whatever you want with it... well... the things we always do ;)

**Comment by dmi3kno** [comment]
When you write README at 4:26 am all sorts of strange things are happening. Accidentally added `echo=FALSE` instead of `message=FALSE` in the package loading chunk. All done, closing the issue!

**Comment by maelle** [comment]
😴 I did wonder why you had written `echo=FALSE` in the first place!

Thanks for the new README version!
